### ISSUE TITLE
Cannot use remotedns.php via docker-apache container

### ISSUE THREAD

**Issue by Jeltel** [mbchristoff/transip-ddns#1]
I'm trying to run your program in docker, but I'm running into issues.

You say to edit files for external access to edit the key in remotedns.php. But that is not accessible via the docker container. Can you add the key as an environment variable?

**Comment by mbchristoff** [comment]
I'm building a new image which enables you to set a remote key as a variable:
```
-e REMOTEKEY=mysupersecurekey
```

During testing I noticed that the container would give back my internal docker ip instead of the real external ip-address.
I'll research how to fix that issue, when using host network I dit manage to get this setup to work properly but it will not be encrypted as it's running on http.

**Comment by Jeltel** [comment]
Thanks :)

The docker not having a https is not an issue for me, since I would be running this behind a proxy with a certificate.

The issue I'm thinking about is that the supersecret key is directly in the url. Still thinking about that. Because with that key you can change the IP of a domain to any IP you'd want.

If it was only for my local machine, there wouldn't be an issue. But it's for someone else with a dynamic IP-address. And it's way easier to host the application on my side, so I can maintain it. Maybe I could run it on the synology NAS there. Testing it here does give back the right result as it seems.

**Comment by mbchristoff** [comment]
> The issue I'm thinking about is that the supersecret key is directly in the url. Still thinking about that. Because with that key you can change the IP of a domain to any IP you'd want.

I could turn this into a POST command, the reasoning behind using a key the url instead of basic auth or POST was that I wanted to make it easy to use and this was easier to use in a browser.

**Comment by Jeltel** [comment]
That is very true. But it also leads to a loss of security. Because the superlong apikey of transip which is used to get a token, is replaced by a static single string value in the URL.

I'm happy for now with the synology version. That works fine. So I'll stick with that one :)
